int plotclass(){
    TFile * rfile = new TFile("out_boosted_AtKt4_and_10_run_33_pp2y02tt_y0_1000GeV_NLO_14TeV_ATLAS_test.root","read");
    TTree * tree = (TTree*)rfile->Get("LJet_TrimmedP4_5");
    TH2D * mass_vs_class = new TH2D("mass_vs_class","mass_vs_class", 100, 0, 2000,55, 0, 55); 
    TH1D * MLclass = new TH1D("MLclass","MLclass", 55, 0, 55); 
    tree->Draw("class:inv_mass >> mass_vs_class", "class > 0","Q");
    tree->Draw("class >> MLclass", "","Q");

mass_vs_class->GetYaxis()->SetBinLabel(1,"None");
mass_vs_class->GetYaxis()->SetBinLabel(2 ,"ll");
mass_vs_class->GetYaxis()->SetBinLabel(3 ,"lt");
mass_vs_class->GetYaxis()->SetBinLabel(4 ,"lw");
mass_vs_class->GetYaxis()->SetBinLabel(5 ,"tl");
mass_vs_class->GetYaxis()->SetBinLabel(6 ,"tt");
mass_vs_class->GetYaxis()->SetBinLabel(7 ,"tw");
mass_vs_class->GetYaxis()->SetBinLabel(8 ,"wl");
mass_vs_class->GetYaxis()->SetBinLabel(9 ,"wt");
mass_vs_class->GetYaxis()->SetBinLabel(10,"lll");
mass_vs_class->GetYaxis()->SetBinLabel(11,"llt");
mass_vs_class->GetYaxis()->SetBinLabel(12,"llw");
mass_vs_class->GetYaxis()->SetBinLabel(13,"ltl");
mass_vs_class->GetYaxis()->SetBinLabel(14,"ltt");
mass_vs_class->GetYaxis()->SetBinLabel(15,"ltw");
mass_vs_class->GetYaxis()->SetBinLabel(16,"lwl");
mass_vs_class->GetYaxis()->SetBinLabel(17,"lwt");
mass_vs_class->GetYaxis()->SetBinLabel(18,"lww");
mass_vs_class->GetYaxis()->SetBinLabel(19,"tll");
mass_vs_class->GetYaxis()->SetBinLabel(20,"tlt");
mass_vs_class->GetYaxis()->SetBinLabel(21,"tlw");
mass_vs_class->GetYaxis()->SetBinLabel(22,"ttl");
mass_vs_class->GetYaxis()->SetBinLabel(23,"twl");
mass_vs_class->GetYaxis()->SetBinLabel(24,"wll");
mass_vs_class->GetYaxis()->SetBinLabel(25,"wlt");
mass_vs_class->GetYaxis()->SetBinLabel(26,"wlw");
mass_vs_class->GetYaxis()->SetBinLabel(27,"wtl");
mass_vs_class->GetYaxis()->SetBinLabel(28,"wwl");
mass_vs_class->GetYaxis()->SetBinLabel(29,"llll");
mass_vs_class->GetYaxis()->SetBinLabel(30,"lllt");
mass_vs_class->GetYaxis()->SetBinLabel(31,"lllw");
mass_vs_class->GetYaxis()->SetBinLabel(32,"lltl");
mass_vs_class->GetYaxis()->SetBinLabel(33,"lltt");
mass_vs_class->GetYaxis()->SetBinLabel(34,"lltw");
mass_vs_class->GetYaxis()->SetBinLabel(35,"llwl");
mass_vs_class->GetYaxis()->SetBinLabel(36,"llwt");
mass_vs_class->GetYaxis()->SetBinLabel(37,"ltll");
mass_vs_class->GetYaxis()->SetBinLabel(38,"ltlt");
mass_vs_class->GetYaxis()->SetBinLabel(39,"ltlw");
mass_vs_class->GetYaxis()->SetBinLabel(40,"lttl");
mass_vs_class->GetYaxis()->SetBinLabel(41,"ltwl");
mass_vs_class->GetYaxis()->SetBinLabel(42,"lwll");
mass_vs_class->GetYaxis()->SetBinLabel(43,"lwtl");
mass_vs_class->GetYaxis()->SetBinLabel(44,"lwwl");
mass_vs_class->GetYaxis()->SetBinLabel(45,"tlll");
mass_vs_class->GetYaxis()->SetBinLabel(46,"tllt");
mass_vs_class->GetYaxis()->SetBinLabel(47,"tllw");
mass_vs_class->GetYaxis()->SetBinLabel(48,"tltl");
mass_vs_class->GetYaxis()->SetBinLabel(49,"tlwl");
mass_vs_class->GetYaxis()->SetBinLabel(50,"ttll");
mass_vs_class->GetYaxis()->SetBinLabel(51,"twll");
mass_vs_class->GetYaxis()->SetBinLabel(52,"wlll");
mass_vs_class->GetYaxis()->SetBinLabel(53,"wllt");
mass_vs_class->GetYaxis()->SetBinLabel(54,"wltl");
mass_vs_class->GetYaxis()->SetBinLabel(55,"wlwl");
mass_vs_class->GetYaxis()->SetBinLabel(56,"wtll");
mass_vs_class->GetXaxis()->SetTitle("Invariant Mass [GeV]");
mass_vs_class->GetYaxis()->SetTitle("ML Class");
mass_vs_class->Draw("colz");

MLclass->GetXaxis()->SetTitle("ML Class");
MLclass->GetXaxis()->SetBinLabel(1,"None");
MLclass->GetXaxis()->SetBinLabel(2 ,"ll");
MLclass->GetXaxis()->SetBinLabel(3 ,"lt");
MLclass->GetXaxis()->SetBinLabel(4 ,"lw");
MLclass->GetXaxis()->SetBinLabel(5 ,"tl");
MLclass->GetXaxis()->SetBinLabel(6 ,"tt");
MLclass->GetXaxis()->SetBinLabel(7 ,"tw");
MLclass->GetXaxis()->SetBinLabel(8 ,"wl");
MLclass->GetXaxis()->SetBinLabel(9 ,"wt");
MLclass->GetXaxis()->SetBinLabel(10,"lll");
MLclass->GetXaxis()->SetBinLabel(11,"llt");
MLclass->GetXaxis()->SetBinLabel(12,"llw");
MLclass->GetXaxis()->SetBinLabel(13,"ltl");
MLclass->GetXaxis()->SetBinLabel(14,"ltt");
MLclass->GetXaxis()->SetBinLabel(15,"ltw");
MLclass->GetXaxis()->SetBinLabel(16,"lwl");
MLclass->GetXaxis()->SetBinLabel(17,"lwt");
MLclass->GetXaxis()->SetBinLabel(18,"lww");
MLclass->GetXaxis()->SetBinLabel(19,"tll");
MLclass->GetXaxis()->SetBinLabel(20,"tlt");
MLclass->GetXaxis()->SetBinLabel(21,"tlw");
MLclass->GetXaxis()->SetBinLabel(22,"ttl");
MLclass->GetXaxis()->SetBinLabel(23,"twl");
MLclass->GetXaxis()->SetBinLabel(24,"wll");
MLclass->GetXaxis()->SetBinLabel(25,"wlt");
MLclass->GetXaxis()->SetBinLabel(26,"wlw");
MLclass->GetXaxis()->SetBinLabel(27,"wtl");
MLclass->GetXaxis()->SetBinLabel(28,"wwl");
MLclass->GetXaxis()->SetBinLabel(29,"llll");
MLclass->GetXaxis()->SetBinLabel(30,"lllt");
MLclass->GetXaxis()->SetBinLabel(31,"lllw");
MLclass->GetXaxis()->SetBinLabel(32,"lltl");
MLclass->GetXaxis()->SetBinLabel(33,"lltt");
MLclass->GetXaxis()->SetBinLabel(34,"lltw");
MLclass->GetXaxis()->SetBinLabel(35,"llwl");
MLclass->GetXaxis()->SetBinLabel(36,"llwt");
MLclass->GetXaxis()->SetBinLabel(37,"ltll");
MLclass->GetXaxis()->SetBinLabel(38,"ltlt");
MLclass->GetXaxis()->SetBinLabel(39,"ltlw");
MLclass->GetXaxis()->SetBinLabel(40,"lttl");
MLclass->GetXaxis()->SetBinLabel(41,"ltwl");
MLclass->GetXaxis()->SetBinLabel(42,"lwll");
MLclass->GetXaxis()->SetBinLabel(43,"lwtl");
MLclass->GetXaxis()->SetBinLabel(44,"lwwl");
MLclass->GetXaxis()->SetBinLabel(45,"tlll");
MLclass->GetXaxis()->SetBinLabel(46,"tllt");
MLclass->GetXaxis()->SetBinLabel(47,"tllw");
MLclass->GetXaxis()->SetBinLabel(48,"tltl");
MLclass->GetXaxis()->SetBinLabel(49,"tlwl");
MLclass->GetXaxis()->SetBinLabel(50,"ttll");
MLclass->GetXaxis()->SetBinLabel(51,"twll");
MLclass->GetXaxis()->SetBinLabel(52,"wlll");
MLclass->GetXaxis()->SetBinLabel(53,"wllt");
MLclass->GetXaxis()->SetBinLabel(54,"wltl");
MLclass->GetXaxis()->SetBinLabel(55,"wlwl");
MLclass->GetXaxis()->SetBinLabel(56,"wtll");


//MLclass->Draw("hist");
}

