#!/bin/bash

root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_dphill_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_dphill_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_mupos_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_mupos_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_muneg_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_muneg_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_ptdw_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_ptdw_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_ptup_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_ptup_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_mll_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_mll_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_noIP_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_noIP_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_isoTight_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_HI_isoTight_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_STAT_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_STAT_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_TOTSYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_ScaleFactor_TOTSYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_dphill_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_dphill_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_mupos_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_mupos_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_muneg_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_muneg_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_ptdw_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_ptdw_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_ptup_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_ptup_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_mll_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_mll_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_noIP_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_noIP_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_isoTight_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_HI_isoTight_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_STAT_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_STAT_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_TOTSYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_DataEfficiency_TOTSYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_dphill_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_dphill_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_mupos_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_mupos_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_muneg_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_muneg_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_ptdw_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_ptdw_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_ptup_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_ptup_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_mll_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_mll_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_noIP_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_noIP_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_isoTight_SYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_HI_isoTight_SYS_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_STAT_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_STAT_1UP_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_TOTSYS_1DN_noDDBkg.root\")"
root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_pub_all_stat/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_comb_MCEfficiency_TOTSYS_1UP_noDDBkg.root\")"

# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_dphill_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_dphill_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_mupos_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_mupos_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_muneg_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_muneg_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_ptdw_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_ptdw_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_ptup_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_ptup_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_mll_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_mll_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_noIP_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_noIP_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_isoTight_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_HI_isoTight_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_STAT_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_STAT_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_TOTSYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_ScaleFactor_TOTSYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_dphill_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_dphill_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_mupos_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_mupos_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_muneg_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_muneg_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_ptdw_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_ptdw_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_ptup_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_ptup_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_mll_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_mll_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_noIP_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_noIP_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_isoTight_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_HI_isoTight_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_STAT_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_STAT_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_TOTSYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_DataEfficiency_TOTSYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_dphill_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_dphill_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_mupos_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_mupos_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_muneg_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_muneg_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_ptdw_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_ptdw_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_ptup_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_ptup_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_mll_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_mll_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_noIP_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_noIP_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_isoTightTrackOnly_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_isoTightTrackOnly_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_isoTight_SYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_HI_isoTight_SYS_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_STAT_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_STAT_1UP_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_TOTSYS_1DN_noDDBkg.root\")"
# root -l -q "./PlotTrigger.C(\"./new_SFs_v8/eff_trig_pPb2D_coarse_v9/Eff_etaphi_coarse_Endcap_QualityMedium_Endcap_HLT_mu15_OR_HLT_mu15_L1MU6_OR_HLT_mu15_L1MU10_MCEfficiency_TOTSYS_1UP_noDDBkg.root\")"